# Numpy

In [5]:
import numpy as np

In [6]:
print('Numpy Version:', np.__version__)

Numpy Version: 2.3.4


In [7]:
arr_ld = np.array([1, 2, 3, 4, 5])

In [8]:
print(arr_ld)

[1 2 3 4 5]


In [9]:
print(type(arr_ld))

<class 'numpy.ndarray'>


In [10]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [11]:
zero_array = np.zeros((3,4))
print(zero_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
const_array = np.full((3,4), 5)
print(const_array)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


# Array  Attributes

In [13]:
const_array.shape

(3, 4)

In [14]:
const_array.dtype

dtype('int64')

In [15]:
const_array.nbytes

96

## Array Operations

In [16]:
a = np.array([[10,20,30,40],[2,4,6,8],[5,10,15,20]])
b = np.array([1,2,3,4])
c = np.array([1])

In [17]:
print(a + b)

[[11 22 33 44]
 [ 3  6  9 12]
 [ 6 12 18 24]]


In [18]:
print(a - b)

[[ 9 18 27 36]
 [ 1  2  3  4]
 [ 4  8 12 16]]


In [19]:
print(a + c)

[[11 21 31 41]
 [ 3  5  7  9]
 [ 6 11 16 21]]


In [20]:
print(a * 2)

[[20 40 60 80]
 [ 4  8 12 16]
 [10 20 30 40]]


### Statistics

In [21]:
print(np.mean(a))

14.166666666666666


In [22]:
print(np.sum(a))

170


In [23]:
print(np.average(a))

14.166666666666666


In [24]:
for row in a.T:
    print(np.mean(row))

5.666666666666667
11.333333333333334
17.0
22.666666666666668


In [25]:
for row in a.T:
    print(row)

[10  2  5]
[20  4 10]
[30  6 15]
[40  8 20]


In [26]:
print(np.mean(a,axis=0))

[ 5.66666667 11.33333333 17.         22.66666667]


In [37]:
a = np.array([[[10,20],[30,40]],[[2,4],[6,8]],[[5,10],[15,20]]])

print(a.shape)
print(f'{a}\n ending')
print(np.mean(a, axis=2))

(3, 2, 2)
[[[10 20]
  [30 40]]

 [[ 2  4]
  [ 6  8]]

 [[ 5 10]
  [15 20]]]
 ending
[[15.  35. ]
 [ 3.   7. ]
 [ 7.5 17.5]]


In [38]:
a = np.array([[10,20,30,40],[2,4,6,8],[5,10,15,20]])

print(a[0,:])



[10 20 30 40]


In [39]:
a = np.array([[10,20,30,40],[2,4,6,8],[5,10,15,20]])

print(a[0,:2,])

[10 20]


In [40]:
print(a[0, 1:3])

[20 30]


In [41]:
print(a[:, 1:3])

[[20 30]
 [ 4  6]
 [10 15]]


### Masking and Filtering

In [42]:
arr = np.array([10,20,30,40,50,60,70,80,90,100])

mask = arr > 20
print(mask)

[False False  True  True  True  True  True  True  True  True]


In [43]:
arr[arr >= 20]

array([ 20,  30,  40,  50,  60,  70,  80,  90, 100])

In [44]:
view = arr[:4]
print(view)

[10 20 30 40]


In [45]:
view[0] = 100
print(view)

[100  20  30  40]


In [47]:
print(arr)

[100  20  30  40  50  60  70  80  90 100]


### A note about copies vs views

In [50]:
view = arr[2:5]
print(view)

[30 40 50]


In [52]:
view[0] = 100
print(view)

[100  40  50]


In [53]:
print(arr)

[100  20 100  40  50  60  70  80  90 100]


### Saving Numpy arrays

In [54]:
np.save('the array.npy', arr)

In [55]:
newArray = np.load('the array.npy')
print(newArray)

[100  20 100  40  50  60  70  80  90 100]
